# Generated by Django 2.0.4 on 2018-04-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180403_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Choice'),
            preserve_default=False,
        ),
    ]
