# Generated by Django 2.0.4 on 2018-04-04 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20180404_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz'),
            preserve_default=False,
        ),
    ]
