# Generated by Django 2.0.4 on 2018-04-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_questionresponse_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.Quiz'),
        ),
    ]
