# Generated by Django 2.0.4 on 2018-04-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20180412_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
